<?php

/**
 * Implements hook_views_data_alter().
 */
function magazinesort_views_data_alter(array &$data) {

  $data['node__field_event_date']['evento'] = array(
    'title' => t('Custom evento sort'),
    'group' => t('Content'),
    'help' => t('Sort news by past/future, then distance from now.'),
    'sort' => array(
      'field' => 'field_event_date_value',
      'id' => 'evento',
    ),
  );

}

